name: Publish

on:
  push:
    branches:
      - dev

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello World
        run: echo "Hello World"
      - name: Debug info
        run: |
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow name: ${{ github.event.workflow_run.name }}"
          echo "Workflow status: ${{ github.event.workflow_run.status }}"
          echo "${{github.event_name}} == 'pull_request' && ${{github.event.action}} == 'closed' && ${{github.event.pull_request.merged}} == true== true"
