name: Publish

on:
  push:
    branches: [dev]
  # pull_request:
  #   branches: '*'
# name: Hello World

# on:
#   push:
#     branches:
#       - dev

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello World
        run: echo "Hello World"
