name: Update cms/master

on:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed
  # push:
  #   branches:
  #     - dev


jobs:
  update-main:
    name: Merge dev into main
    if: ${{ github.event.workflow_run.conclusion == 'succeeded' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.TOKEN }}
          source: 'dev'
          target: 'main'


