name: Action-Automerge

on:
  push:
    branches:
      - dev
      - main

jobs:
  update-main:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    name: Merge dev into main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Merge dev into main
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          source: 'dev'
          target: 'main'
