name: Update cms/master

on:
  push:
    branches:
      - dev


jobs:
  update-main:
    name: Merge dev into main
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.TOKEN }}
          source: 'dev'
          target: 'main'


