name: Action-Automerge

on:
  push:
    branches:
      - dev
      - main
    

jobs:
  update-main:
    # if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    # name: Merge dev into main
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.TOKEN }}


    steps:
      - name: Slack notification of pipeline
        uses: act10ns/slack@v2
        with:
          status: starting
          channel: 'T0H734THC'
          message: Backend Deployment Started..
      - name: Checkout repository
        uses: actions/checkout@v2
  
      # - name: Merge dev into main
      #   uses: mtanzi/action-automerge@v1
      #   id: merge
      #   with:
      #     github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     source: 'dev'
      #     target: 'main'
      - name: pipeline status send on Slack
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: 'T0H734THC'
        if: always()
